name: github-actions
run-name: is learning GitHub Actions
on: [push]
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: python -m pip install requirements.txt
      - run: python Tests/APITests/test_user_service