name: regression

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: run app
      run: |
        python app.py
        

    - name: web tests
      run: |
        python -m pytest --import-mode=append Tests/UITests/
