name: regression

jobs:
  build:
    name: Regression

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: run app
        run: |
          python app.py

      - name: web tests
        run: |
          python -m pytest --import-mode=append Tests/UITests/